/** Stable form field keys (data-field / name) → normalized label for Brevo mapping */
export const FIELD_KEY_TO_LABEL = {
  first_name: 'first name',
  last_name: 'last name',
  email: 'email address',
  phone: 'contact number',
  street_address: 'street address',
  address_line2: 'address line 2',
  city: 'city',
  state: 'state',
  zip: 'zip code',
  company_name: 'company name',
  job_title: 'job title',
  company_website: 'company website',
  branch_of_service: 'branch of service',
  military_status: 'current military status',
  discharge_status: 'discharge status',
  rank: 'rank at discharge / current rank',
  enlistment_date: 'enlistment date',
  separation_date: 'expected / actual separation date',
  mos_afsc_rate: 'mos / afsc / rate',
  aviation_maint_exp: 'aviation maintenance experience',
  mechanical_exp: 'general mechanical experience',
  enrolled_training: 'currently enrolled in training program?',
  av_mech_certs: 'completed any aviation / mechanical certifications?',
  faa_written_exams: 'faa written exams completed',
  faa_oral_practical: 'scheduled for faa oral & practical exam?',
  employment_status: 'current employment status',
  willing_relocate: 'willing to relocate?',
  preferred_locations: 'preferred geographic locations',
  resume_prepared: 'resume prepared?',
  mentorship_interest: 'interested in mentorship / career guidance?',
  support_needed: 'support needed',
  referral_source: 'how did you hear about win?',
  additional_info: 'additional information',
  org_type: 'organization type',
  currently_hiring: 'currently hiring?',
  hiring_locations: 'geographic hiring locations',
  annual_hires: 'anticipated annual hires',
  roles_hiring: 'roles most frequently hiring for',
  hire_veterans: 'currently hire veterans / transitioning military?',
  preferred_contact: 'preferred contact method',
  partnership_interest: 'partnership interest with win',
  areas_of_interest: 'areas of interest to discuss with win',
  schedule_call: 'schedule an introductory call with win?',
  support_types: 'type of support interested in',
  recurring_support: 'interested in recurring support?',
  sponsorship_packages: 'interested in sponsorship / partnership packages?',
  contribution_level: 'estimated level of support / contribution interest',
  engagement_preferences: 'how would you prefer to stay engaged with win?',
};
